language: c

os:
  - linux
  - osx

dist: trusty

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make install; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make install; fi

notifications:
  email: false
